### ISSUE TITLE
Add internationalization support

### ISSUE THREAD

**Issue by Oklyne** [Insprill/dv-multiplayer#14]

**Comment by KCHARRO** [comment]
Hello, I am available for translation into Spanish....

**Comment by Insprill** [comment]
Thank you all for the offers! This has been added in 87cbb27dfdf57efa99b7f902f4eb3463d7daeb3f.

The translation file can be found [here](https://github.com/Insprill/dv-multiplayer/blob/master/locale.csv) at the root of the repository, in the `locale.csv` file. The file is simple, with each row being a piece of text and each column being a different language. Only languages supported by Derail Valley are listed in the file, so if a language you want to translate to isn't present, consider contacting Altfuture about becoming a translator for the game.

If anyone has any questions or problems translating, feel free to ask here or, preferably, in the  [Altfuture Discord Server](https://discord.gg/wFA2A2GEng).
