### ISSUE TITLE
Port-forwarding Alternatives & Server Suggestions

### ISSUE THREAD

**Issue by HStrawberryDev** [Insprill/dv-multiplayer#20]
# No Portforwarding
For players that cannot portforward and just want to simply play with their friends, they can use virtual local networks.
Luckily Zerotier is a good example of that which provides a simple interface.

(One person who is the network manager is the only person who sees everyone's actual real IP, and can figure out who is the one who hosts the game, and connect via Zerotier's local IP.)

![image](https://github.com/Insprill/dv-multiplayer/assets/122948013/b92ff6ba-7621-4259-bd47-769d54b6a3e9)

It also works if one person is the host and the manager for the network.
All other players connect using the Managed IP.

+ This also works with many other games and applications that require portforwarding!

# Server Suggestions
Dedicated Servers, though it requires the game itself as well, would be an amazing option for those who play with a group but don't want to rely on one person to save or even save themselves. Now I don't really know how Dedicated Servers would really work, because most games have them as they're native to the game rather than it being an addon/mod.

**Comment by Insprill** [comment]
LiteNetLib has built-in support for NAT punching, I just haven't gotten around to implementing it yet. If NAT punching doesn't work in some cases, we could also look into implementing UPnP. The Dedicated Server discussion should be held in a dedicated issue.

**Comment by Insprill** [comment]
I'm going to close this for now, although I may add a mention of ZeroTier in the documentation. The discussion for dedicated servers has been moved to #28.
