### ISSUE TITLE
Add a list of dependencies and how to install them to the readme

### ISSUE THREAD

**Issue by t0stiman** [Insprill/dv-multiplayer#32]
I'm trying to build this project and having to guess what dependencies I need based on the code and .csproj. I'm stuck on acquiring I2.Localization, that seems to be a paid Unity plugin...

**Comment by CODEYXone** [comment]
Hi! This seems to be an issue with the Directory.Build.Targets file. Have you checked that the paths listed in the file are correctly set to their corresponding target?

For example:
```
<Project>
    <PropertyGroup>
        <DvInstallDir>C:\SteamLibrary\steamapps\common\Derail Valley</DvInstallDir>
        <UnityInstallDir>C:\Program Files\Unity\Hub\Editor\2019.4.40f1\Editor</UnityInstallDir>
        <ReferencePath>
            $(DvInstallDir)\DerailValley_Data\Managed\;
            $(DvInstallDir)\DerailValley_Data\Managed\UnityModManager\;
            $(UnityInstallDir)\Data\Managed\
        </ReferencePath>
        <AssemblySearchPaths>$(AssemblySearchPaths);$(ReferencePath);</AssemblySearchPaths>
    </PropertyGroup>
</Project>
```
These are the important ones you need to change:
```
<DvInstallDir>C:\SteamLibrary\steamapps\common\Derail Valley</DvInstallDir>
<UnityInstallDir>C:\Program Files\Unity\Hub\Editor\2019.4.40f1\Editor</UnityInstallDir>
```
I2.Localization should be satisfied through $(DvInstallDir)\DerailValley_Data\Managed\


Please make sure that the paths are set correct, as seen in the [Building Documentation](https://dv-mapify.readthedocs.io/en/latest/contributing/building/)

**Comment by t0stiman** [comment]
@CODEYXone thanks, I add re-cloned the repo and forgotten to re-add the ` Directory.Build.Targets` file.
