### ISSUE TITLE
Implement Dependabot 

### ISSUE THREAD

**Issue by GameKuchen** [Insprill/dv-multiplayer#41]
Hi Insprill,

I noticed this project doesn't currently use a tool like Dependabot for dependency management. I was wondering if you'd be interested in considering it.

Dependabot automates keeping dependencies updated and helps identify potential security vulnerabilities. This can save you time and effort in maintaining the project.

Here's some information about Dependabot for your reference: [Link to Dependabot quick start guide](https://docs.github.com/de/code-security/getting-started/dependabot-quickstart-guide)

Thanks for your work on this project!

**Comment by Insprill** [comment]
No
